### ISSUE TITLE
Needs more "why this exists" + user testimonial in README

### ISSUE THREAD

**Issue by LappleApple** [zalando-incubator/remora#12]
@imduffy15 tells me that another company is using this. Please provide some sort of context about how they're using it and what Remora is helping them achieve. This sort of information is very valuable for growing a project. It will potentially inspire others to use it.

**Comment by marky-mark** [comment]
Awesome! Who uses this? What extra information do we need?

**Comment by imduffy15** [comment]
Reached out to all of the external folks who started the project.

Most responded with haven't got a chance to deploy remora yet but it does solve a problem we experience.

We had an issue created awhile back by one of the people who started the projected. They successfully ran remora and handed it over to their monitoring team, however they discontinued using it as they found something that integrated with their monitoring system better - awaiting further feedback.

Contacted the teams within the Dublin office who are using it, waiting on responses of recommendations/testimonials from them.

**Comment by imduffy15** [comment]
Afaik there isn't anything left to be done on this issue. Closing.
