### ISSUE TITLE
Support exporting to CloudWatch

### ISSUE THREAD

**Issue by imduffy15** [zalando-incubator/remora#23]
It would be neat to be able to automatically scale out an ASG of Kafka Consumers based on their consumer group lag.

With Remora at the moment, this would be possible if you had something like lambda to query it on interval and submit the metrics to CloudWatch. However, not all organizations allow usage of lambda. It would be useful if Remora could push these 1) on interval or 2) on request.

**Comment by marky-mark** [comment]
Nice idea mate!

Going further, could create...
* JMX reporter
* Cloudwatch reporter

In addition 
* prometheus format for endpoint (instead of json)

I could make a start at the cloudwatch reporter.

**Comment by imduffy15** [comment]
Sounds good to me!

Would be neat if we could cache those results for serving on http end points and have something in the background updating on schedule. 

Will need a whitelist/blacklist of consumer groups to poll on interval.

**Comment by marky-mark** [comment]
This is the reporter for yammer metrics https://github.com/blacklocus/metrics-cloudwatch. 

We just need to transform the consumer metrics to yammer and hook in the reporter.

**Comment by marky-mark** [comment]
PR submitted
