### ISSUE TITLE
Adding Datadog as a reporting system

### ISSUE THREAD

**Issue by nsanglar** [zalando-incubator/remora#29]
Hi,

First of all, thanks for this small tool, it really helped us to monitor our Kafka applications.

Remora currently supports reporting via HTTP and Cloudwatch, and I would propose to add a new reporting system: [Datadog](https://www.datadoghq.com/). It is straightforward to implement, as there is an integration with Dropwizard metrics.

We already use this integration for our projects, I will post a PR soon.

**Comment by marky-mark** [comment]
Its great to hear that this tool is useful. Thank you for your feedback :)

We can of course investigate to reporting into Datadog. You can submit a PR or I can investigate for you.

**Comment by nsanglar** [comment]
I am currently working on a PR :)
However, I cannot assign myself to this issue (I guess some permission issue), could you do it?

**Comment by marky-mark** [comment]
Probably due to you not being part of the zalando group. I assigned the issue to myself....just send in the PR when ready.

Look forward to it

**Comment by marky-mark** [comment]
Sent you an invite as a collaborator, as soon as you accept I can assign to you

**Comment by marky-mark** [comment]
Would you mind writing a "Testimonial" in the readme? Thanks
