### ISSUE TITLE
Adding total consumer lag per topic

### ISSUE THREAD

**Issue by nsanglar** [zalando-incubator/remora#32]
Currently, remora publishes consumer lag at the partition level.
While it gives detailed information on the consumers, it would be nice to directly have the consumer lag for a topic (by adding the lag of each partition) .

This is helpful when using monitoring services such as datadog, since currently each metric for each partition needs to be aggregated in order to have a quick view on the system health.

**Comment by marky-mark** [comment]
Yea sounds good but as you mentioned the metrics provider can aggregate each partition into a single view.

We could add in our own aggregator but is this really needed?

**Comment by imduffy15** [comment]
This would be really handy for the cloudwatch metrics too

**Comment by nsanglar** [comment]
Actually we are facing the following: we have topics with 64 partitions, so 64 lag metrics that needs to be manually aggregated with datadog for each topic. 
It is almost faster to code it in remora :)

**Comment by marky-mark** [comment]
Ok so, Ian is backing you up :)

I suppose some on the fly aggregation operations shouldn't affect the performance that much.

Are you going to send in a PR or do you want me to do it?

**Comment by nsanglar** [comment]
A PR is on its way :)

**Comment by marky-mark** [comment]
Looking forward to it. Thanks for your help

**Comment by imduffy15** [comment]
Published image registry.opensource.zalan.do/dougal/remora:1.0.1-2-g28d4a69

Thanks for the contribution :)
