### ISSUE TITLE
Datadog dashboard

### ISSUE THREAD

**Issue by simonwahlgren** [zalando-incubator/remora#34]
Hey and thank you for a great project!

I have tried to setup a "dynamic" dashboard in Datadog in the sense that the topics/partitions and consumer group lags are automatically added to a graph. But I can't find a way to use wildcard or regular expressions in the metric name. Have you solved this in a more dynamic way? Or have you manually added all topics/partitions for each consumer group?

Best regards,
Simon

**Comment by nsanglar** [comment]
Hello, 
No in datadog I don't think that you can use wildcards to get metrics unfortunately. However, since the last version of remora there is a metric that gives you the consumer lag for a topic, so you don't need to do it for every partition.

**Comment by simonwahlgren** [comment]
@nsanglar Thanks for the info!

I have done some more research and it seems like other projects utilize tagged metrics to solve this. Each metric is tagged with cluster, topic, consumer and partition. Then you can utilize template variables in Datadog to filter and group metrics. Is this something you have considered adding support for?

**Comment by nsanglar** [comment]
Sure I can take a look and I will come back to you.

**Comment by simonwahlgren** [comment]
Awesome, thanks!

Maybe you will find these projects useful, they both utilize tags:
https://github.com/packetloop/datadog-agent-burrow/
https://github.com/sv3nd/kafka-topic-offset-datadog

**Comment by nsanglar** [comment]
Ok I think I found a way, i'll post a PR when ready :)

**Comment by marky-mark** [comment]
@simonwahlgren Can you write a testimonial on the README.md please? :) 

The PR is ready to merge

**Comment by simonwahlgren** [comment]
@nsanglar @marky-mark This is awesome, thanks a lot! I'll update the testimonial asap! :)
