### ISSUE TITLE
Zalando repository

### ISSUE THREAD

**Issue by simonwahlgren** [zalando-incubator/remora#36]
Hey! 

I have a question regarding your repository `registry.opensource.zalan.do/dougal/remora`. Is it building a new image on every commit? And how are the images tagged? I tried to use the commit hash but it didn't work.

My real problem is that you can't use the `latest` tag with Kubernetes, you must change the tag to pull a new image.

Thanks!
/Simon

**Comment by imduffy15** [comment]
Hey @simonwahlgren 

Its based of the git tag and git hash.

$ pierone latest dougal remora --url registry.opensource.zalan.do
1.0.2-2-g09ac2bc

is the current latest, you should be able to execute the same command if pierone is installed on your machine:

```
$ pip3 install stups-pierone
```

If you views on how we can make this more consumable I'm all ears.

**Comment by marky-mark** [comment]
We could add in tagging the "latest" and push that with the version if that helps?

**Comment by marky-mark** [comment]
Created a PR it's a 1 liner https://github.com/zalando-incubator/remora/pull/37

**Comment by simonwahlgren** [comment]
@imduffy15 Thanks for the explanation! And sorry for my delayed answer...

I think this makes totally sense now. The only piece I was missing was the explanation how to use `pierone`, maybe you could add a section about this or a link in the README?

**Comment by marky-mark** [comment]
@imduffy15 any chance of adding to the readme?

@simonwahlgren We also recently added tag "latest" with every build. See latest on master. Can you add a testimonial too? 

Thanks for the interest. Yes Remora!

**Comment by imduffy15** [comment]
Simple approach to do this is:

```
$ curl https://registry.opensource.zalan.do/teams/dougal/artifacts/remora/tags | jq ".[] | .name"
```

**Comment by imduffy15** [comment]
@marky-mark will update the readme....

**Comment by marky-mark** [comment]
Added readme here https://github.com/zalando-incubator/remora/pull/44

**Comment by imduffy15** [comment]
LGTM @marky-mark going to close off this issue.
