### ISSUE TITLE
Support for brokers which require authentication

### ISSUE THREAD

**Issue by pawelgrzes** [zalando-incubator/remora#42]
Currently it seems to not be possible to use Remora with brokers which require authentication (for example SASL_SSL).
My idea is to extend Remora to have an additional environment variable which would allow to execute behind the scenes a command similar to the following example:

`kafka-consumer-groups --bootstrap-server local:9094 --describe --group my-group --command-config auth.properties`

where `auth.properties` content would look like to the following:
`security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="my-user" password="my-password";
`

**Comment by pawelgrzes** [comment]
I have tried to follow [the contributing instructions](https://github.com/zalando-incubator/remora/blob/master/CONTRIBUTING.md) but it seems I have no rights to assign myself to this issue.
Anyway work-in-progress fork is [here](https://github.com/pawelgrzes/remora/tree/feature/command-config)

**Comment by marky-mark** [comment]
Looks great, thanks for the contribution. I can add you to the list of contributors, I think that should solve the issue...

**Comment by pawelgrzes** [comment]
Guys what is actually the workflow here? 
Should I close it now (PR was merged) or when release is done?

Thx in advance for the answer!

**Comment by dr4ke616** [comment]
Hey @pawelgrzes, I'm not personally aware of any specific workflow. You can probably just close the issue. An image has automatically been deployed to the open source registry with a tag of `1.0.5-1-g03782ad`.

**Comment by pawelgrzes** [comment]
Thx @dr4ke616 Closing then.
