### ISSUE TITLE
Dockerfile in repo?

### ISSUE THREAD

**Issue by bradurani** [zalando-incubator/remora#52]
Any reason the Dockerfile is not in the repo? We'd love to be able to build our own images

**Comment by nsanglar** [comment]
Hello, there is nodocker file because the whole docker config is handled via SBT

**Comment by marky-mark** [comment]
Instructions are in the readme https://github.com/zalando-incubator/remora#build

**Comment by marky-mark** [comment]
You can see the dockerfile generated in the target directory. Nothing stopping you from building this application whichever way you like to including your own base dockerfile, but this will all that will be provided. The image itself is already built and is public for you too.

Thanks for the interest in remora
