### ISSUE TITLE
Kafaka 2.0 support

### ISSUE THREAD

**Issue by ericfgarcia** [zalando-incubator/remora#53]
My team is currently using Burrow and we are running into some possible scaling issues.  We found your project while looking at other tools and are interested in looking at it.  We are also looking at an upgrade to Kafka 2.0 and were wondering if support for 2.0 is on you near term roadmap.

Thanks,
Eric Garcia

**Comment by marky-mark** [comment]
PR https://github.com/zalando-incubator/remora/pull/56

**Comment by marky-mark** [comment]
[Kafka 2X support](https://github.com/zalando-incubator/remora/releases/tag/v1.0.7)
