### ISSUE TITLE
Prometheus Exporter

### ISSUE THREAD

**Issue by Zero-2** [zalando-incubator/remora#58]
Hi all,
i think remora is a good alternatives to other lag monitoring tools.
There's some chance to have a prometheus metrics exporter?
Or someone can help me to write it by myself?

Thanks

**Comment by marky-mark** [comment]
By all means go ahead 👍 

Someone else already added datadog here https://github.com/zalando-incubator/remora/blob/master/src/main/scala/reporter/RemoraDatadogReporter.scala

or add in the prometheus node exporter to the docker image...whatever ya fancy

**Comment by omarsmak** [comment]
I am not sure if that is what you are looking for but I have wrote [this simple client](https://github.com/omarsmak/kafka-consumer-lag-monitoring) to push the consumer lags to Prometheus and potentially to more output mediums in the future, it uses Java Kafka AdminClient along with the consumer client, it is not as comprehensive as remora but it is simple and I'd like to keep it in that way :)

**Comment by Zero-2** [comment]
I will try it.👍 
Thank you

**Comment by elkozmon** [comment]
Hi there.

I added a [simple Prometheus reporter](https://github.com/elkozmon/remora/blob/feature/prometheus-reporter/src/main/scala/reporter/RemoraPrometheusReporter.scala). As opposed to the Datadog's it does not support prefixing nor filtering metrics at the moment.

If you're interested I can submit a PR.

**Comment by jocelyndrean** [comment]
@elkozmon Thanks for sharing. Very interesting ! You should submit a PR :)
