### ISSUE TITLE
Documentation: Creating a connection between the fetcher and gafana

### ISSUE THREAD

**Issue by monksy** [zalando-incubator/remora#59]
It looks like from the screenshot that you're using grafana to show the information. Could you provide information about how to connect those 2 with the remora endpoint?

**Comment by marky-mark** [comment]
@imduffy15 wrote a remora fetcher https://github.com/imduffy15/remora-fetcher which has a docker compose combining the 2.

https://github.com/imduffy15/remora-fetcher/blob/master/docker-compose.yml

**Comment by monksy** [comment]
But that doesn't describe how to setup the graphs, or how to query for it.

**Comment by marky-mark** [comment]
If you look at remora-fetcher.py the script pulls data and pushes this into KairoDB. From kairoDB the metrics can be queried by grafana.

**Comment by cricket007** [comment]
I believe the question is actually looking for the Grafana query syntax, or downloadable/importable dashboard perhaps?

**Comment by monksy** [comment]
Yep.. need some examples

**Comment by marky-mark** [comment]
Ok I don’t believe that’s there, unless Ian adds the graph to import from his history. why don’t you try google for some grafana tutorials (it’s really not that difficult) you could use remora fetcher for data and add the graph data to the remora fetcher project.
