### ISSUE TITLE
Clarify Burrow "performance problems"

### ISSUE THREAD

**Issue by cricket007** [zalando-incubator/remora#60]
In the README, says "performance problems" were experienced with Burrow, therefore this repo was created. 

I assume that the issues were with management of the Golang client/API, as compared to the JVM Kafka clients, but if so or even not, can some clarification be added as to why someone may "chose" this over the alternative of Burrow?

**Comment by marky-mark** [comment]
Hey,

So basically burrow would just shut down after an unknown amount with no error stack, alert or sign of error. We really had no idea why. At the time it took shorter time to build this than figure out what is happening in Go.

Over time people started adding parts that they needed for various monitoring systems and we continued to upgrade kafka versions.

Thanks for the interest

Mark

**Comment by cricket007** [comment]
I don't suppose this information could be placed in the README?

**Comment by marky-mark** [comment]
I do suppose i could, here's a little more info as to why this project was created as seen in the PR below.

https://github.com/zalando-incubator/remora/pull/61

You are of course welcome to contribute to this project if you feel you require something to fit your needs or if documentation needs some additions.

Thanks
