### ISSUE TITLE
Support Multiple Clusters

### ISSUE THREAD

**Issue by OneCricketeer** [zalando-incubator/remora#64]
Rather than deploying one Remora instance per cluster, how about one instance that can access multiple clusters?

**Proposal**

1. Update configuration

```
kafka [
  {
    name = "clusterA"
    endpoint = "localhost:9092"
    endpoint = ${?KAFKA_ENDPOINT[0]}
    command {
      config = ""
      config = ${?KAFKA_COMMAND_CONFIG[0]}
    }
  },
  {
    name = "clusterB"
    endpoint = "localhost:6667"
    endpoint = ${?KAFKA_ENDPOINT[1]}
    command {
      config = ""
      config = ${?KAFKA_COMMAND_CONFIG[1]}
    }
  }
}
```

2. Update REST resources
  - If `len(clusters) == 1`, take current behavior (possibly via redirects)
  - Else, require `/clusterX/` in route, and 404 for any cluster name not found

**Comment by marky-mark** [comment]
Looks like a good idea if you need it, most teams would have 1 kafka cluster. 

If you were to do this perhaps an array would be better.
