### ISSUE TITLE
Make logging level configurable

### ISSUE THREAD

**Issue by ndomar** [zalando-incubator/remora#72]
Hey, as of now Remora is generating a lot of logs on debug level, is it currently to possible to manage the log level via configuration?

**Comment by cricket007** [comment]
Same as #73 , you can set your own levels with your own logging file

http://logback.qos.ch/manual/configuration.html#configFileProperty

**Comment by dtrsan** [comment]
This PR allows to configure root log level.
https://github.com/zalando-incubator/remora/pull/81
