### ISSUE TITLE
Update kafka dependency to 2.0.1

### ISSUE THREAD

**Issue by tr4r3x** [zalando-incubator/remora#74]
We have encountered `NullPointerException` when getting lags. Stack trace could be found in issue #67 . This issue itself is described in [KAFKA-7044](https://issues.apache.org/jira/browse/KAFKA-7044) ([fix](https://github.com/apache/kafka/pull/5627)).

According to [KAFKA-7044](https://issues.apache.org/jira/browse/KAFKA-7044) it was fixed in versions  1.1.2, 2.0.1, 2.1.0, but remora uses [2.0.0](https://github.com/zalando-incubator/remora/blob/master/build.sbt#L58). The latest minor version which is available is [2.0.1](https://mvnrepository.com/artifact/org.apache.kafka/kafka)

**Comment by patelprakashp** [comment]
@cricket007 @imduffy15 - Can some please update kafka version to higher than 2.0 , i also get NPE on round robin assignment. We should update kafka client to 2.4

**Comment by cricket007** [comment]
Happy to review a PR

**Comment by patelprakashp** [comment]
This should be closed as version is updated and fix the broken build because of distro change in travis.
